version: "3.8"

services:
  app:
    container_name: mindforge-server-llm_app
    image: ${IMAGE_NAME:-mindforge-server-llm:cpu}
    build:
      context: .
    volumes:
      - ./prompts:/prompts:ro
    environment:
      - N_PARALLEL=${N_PARALLEL:-1}
      - PORT=3000
    networks:
      - llm-net
    expose:
      - "3000"
    restart: unless-stopped

  caddy:
    container_name: mindforge-server-llm_caddy
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log/caddy:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - app
    networks:
      - llm-net
    restart: unless-stopped

networks:
  llm-net:
    driver: bridge

volumes:
  caddy_data: {}
  caddy_config: {}
