version: "3.8"

services:
  app:
    container_name: mindforge-server-llm_rust
    image: ${IMAGE_NAME:-mindforge-server-llm-rust:latest}
    build:
      context: ./rust-server
      dockerfile: Dockerfile
    volumes:
      - ./prompts:/prompts:ro
      - ./models:/models:ro
    environment:
      - N_PARALLEL=${N_PARALLEL:-4}
      - N_THREADS=${N_THREADS:-0}
      - CTX=${CTX:-2048}
      - N_BATCH=${N_BATCH:-256}
      - PORT=3000
      - MODEL_PATH=/models/${MODEL_FILE:-model.gguf}
      - RUST_LOG=info
    networks:
      - llm-net
    expose:
      - "3000"
    restart: unless-stopped
    # CPU limits for production
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G

  caddy:
    container_name: mindforge-server-llm_caddy
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log/caddy:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - app
    networks:
      - llm-net
    restart: unless-stopped

networks:
  llm-net:
    driver: bridge

volumes:
  caddy_data: {}
  caddy_config: {}
